import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["cyrillic"] });

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        backgroundImage: 'url("/auth/banner.webp")',
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        minHeight: "100vh",
      }}
      className="min-w-screen min-h-screen"
    >
      {children}
    </div>
  );
}
